# Generated by Django 5.0.6 on 2024-05-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210801_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('ethnicity', models.CharField(choices=[('AA', 'African American'), ('AI', 'American Indian or Native Alaskan'), ('API', 'Asian or Pacific Islander'), ('HL', 'Hispanic-Latino'), ('W', 'White'), ('O', 'Other')], max_length=3)),
                ('religion', models.CharField(max_length=100)),
                ('open_to_religious_school', models.BooleanField(default=False)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('annual_family_income', models.CharField(choices=[('0-10k', '0 - 10,000'), ('10k-30k', '10,001 - 30,000'), ('30k-50k', '30,001 - 50,000'), ('50k-75k', '50,001 - 75,000'), ('75k-100k', '75,001 - 100,000'), ('100k+', '100,000+')], max_length=20)),
                ('first_generation_college_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
