# Generated by Django 5.0.6 on 2024-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(choices=[('', 'Choose Education Level'), ('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(choices=[('', 'Choose a Major'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Business Administration', 'Business Administration'), ('Psychology', 'Psychology'), ('Biology', 'Biology'), ('Mathematics', 'Mathematics'), ('English Literature', 'English Literature'), ('History', 'History'), ('Art', 'Art'), ('Music', 'Music'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
